model:
  name: cheby_aspire
  alpha: 500.0
  degree: 30

  # Beta: Spectral Penalty Selection
  # 'auto_bias': Theoretically derived beta = gamma / (1+gamma)
  # 'auto_compromise': Theoretically derived beta = gamma / 2
  # beta: "auto_bias"
  beta: "auto_compromise"

  lambda_max_estimate: "auto"
  visualize: true # Skip heavy visualizations for Bayesian searches
device: auto
