model:
  name: csar
  embedding_dim: 64
  orth_loss_weight:
    - 0.1
    - 0.5
    - 1.0
  num_interests:
    - 64
    - 96
  scale: true
  zscore: false
  emb_dropout: 0.0

train:
  embedding_l2: 0.0001
  weight_decay: 0.0
  epochs: 500
  batch_size: 1024
  lr: 0.001
  optimizer: adam
  loss_type: pointwise
  num_negatives: 1
  early_stop_patience: 40
device: auto
