# Amazon Music
dataset_name: "amazon_music"
data_path: "/Users/leejongmin/code/recsys_framework/data/amazon_music/Amazon_Digital_Music.inter"
separator: "\t"
columns: ["user_id", "item_id", "rating", "timestamp"]

rating_threshold: null
min_user_interactions: 3
min_item_interactions: 3
split_method: "temporal_ratio"
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
