# Amazon Movies & TV
dataset_name: "amazon_tv_movie"
data_path: "./data/amazon_tv_movie/Movies_and_TV.csv"
separator: ","
columns: ["item_id", "user_id", "rating", "timestamp"]

rating_threshold: 4
min_user_interactions: 5
min_item_interactions: 5
split_method: "temporal_ratio"
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
