# 데이터셋 설정
dataset_name: "amazon_books"
data_path: "./data/amazon_electronics/Amazon_Electronics.inter"
separator: "\t"
columns: ["user_id", "item_id", "rating", "timestamp"]

rating_threshold: 4 # 이 값 이상의 평점만 상호작용으로 간주 (임시 비활성화)
min_user_interactions: 5
min_item_interactions: 5
split_method: "temporal_ratio" # Leave-One-Out
train_ratio: 0.8 # 학습 데이터 비율 (LOO에서는 미사용)
valid_ratio: 0.1 # 검증 데이터 비율 (LOO에서는 미사용)
data_cache_path: "./data_cache/" # 데이터셋 전처리 결과를 캐싱할 경로
