# LFM-10M (LFM-1B 1% subset, implicit feedback)
dataset_name: "lfm_10m"
data_path: "./data/lfm-10m/ratings.dat"
separator: "\t"
columns: ["user_id", "item_id", "timestamp", "num_repeat"]
has_header: true

min_user_interactions: 5
min_item_interactions: 5
split_method: "temporal_ratio"
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
