# 데이터셋 설정
dataset_name: "ml-100k"
data_path: "./data/ml100k/u.data"
separator: '\t'
columns: ["user_id", "item_id", "rating", "timestamp"]

# 데이터 전처리 및 분할 설정
rating_threshold: 0
min_user_interactions: 5
min_item_interactions: 5
split_method: "temporal_ratio"
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
