# 데이터셋 설정
dataset_name: "ml-1m"
data_path: "./data/ml1m/ratings.dat"
separator: "::"
columns: ["user_id", "item_id", "rating", "timestamp"]

# 데이터 전처리 및 분할 설정
rating_threshold: 0 # 이 값 이상의 평점만 상호작용으로 간주
min_user_interactions: 5
min_item_interactions: 5
split_method: "temporal_ratio" # 유저별 시간순 비율 분할
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
