# Yelp2018 Dataset Config (Optimized Subset for EASE)
dataset_name: "yelp2018"
data_path: "./data/yelp2018/yelp2018.inter"
separator: "\t"
has_header: True
# user_id item_id rating timestamp useful funny cool review_id
columns:
  [
    "user_id",
    "item_id",
    "rating",
    "timestamp",
    "useful",
    "funny",
    "cool",
    "review_id",
  ]

rating_threshold: null
min_user_interactions: 10 # Already filtered in subset script
min_item_interactions: 10
split_method: "temporal_ratio"
train_ratio: 0.8
valid_ratio: 0.1
data_cache_path: "./data_cache/"
