model:
  name: NeuMF
  embedding_dim_gmf: 32
  embedding_dim_mlp: 32
  mlp_layers:
  - - 64
    - 32
    - 16
train:
  embedding_l2: 0.0001
  weight_decay: 0.0
  epochs: 500
  batch_size: 1024
  lr: 0.001
  optimizer: adam
  loss_type: pairwise
  num_negatives: 4
  negative_sampling_strategy:
  - uniform
  negative_sampling_alpha: 0.75
  early_stop_patience: 40
device: auto
